--CREAZIONE TIPO_ANIMALE

CREATE TABLE TIPO_ANIMALE (
    NOME_TIPO_ANIMALE VARCHAR2(30),
    SPECIE VARCHAR2(30),
    VITA_MEDIA_ANNI NUMBER(5,2),
    MODALITA_RIPRODUZIONE VARCHAR2(15),
    GIORNI_GESTAZIONE NUMBER(3,0),
    UMIDITA_IDEALE NUMBER(3,0) --UMIDITA IN PERCENTUALE
        CONSTRAINT NN_TIPO_ANIMALE_UMIDITA NOT NULL,
    SPAZIO_MINIMO_MQ NUMBER(2,2)
        CONSTRAINT NN_TIPO_ANIMALE_SPAZIO_MINIMO NOT NULL,
    TEMPERATURA_IDEALE NUMBER(3,0) --TEMPERATURA IN KELVIN
        CONSTRAINT NN_TIPO_ANIMALE_TEMPERATURA NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_ANIMALE PRIMARY KEY(NOME_TIPO_ANIMALE),

    --CHECK
    CONSTRAINT CK_TIPO_ANIMALE_VITA_MEDIA_ANNI
        CHECK (VITA_MEDIA_ANNI > 0),
    
    CONSTRAINT CK_TIPO_ANIMALE_MODALITA_RIPRODUZIONE
        CHECK (MODALITA_RIPRODUZIONE IN (
                'OVIPARA', --DEPONE UOVA
                'VIVIPARA', --PARTORISCE FIGLI VIVI
                'OVOVIVIPARA',  --UOVA SI SCHIUDONO ALL'INTERNO DEL CORPO MATERNO
                'PARTENOGENESI', --RIPRODUZIONE ASESSUATA
                'ASESSUATA' --RIPRODUZIONE SENZA FECONDAZIONE
            )),
    
    CONSTRAINT CK_TIPO_ANIMALE_GIORNI_GESTAZIONE
        CHECK (GIORNI_GESTAZIONE > 0),
    
    CONSTRAINT CK_TIPO_ANIMALE_UMIDITA
        CHECK (UMIDITA_IDEALE >= 0 AND UMIDITA_IDEALE <= 100),

    CONSTRAINT CK_TIPO_ANIMALE_SPAZIO_MINIMO
        CHECK (SPAZIO_MINIMO_MQ >0),
    
    CONSTRAINT CK_TIPO_ANIMALE_TEMPERATURA
        CHECK (TEMPERATURA_IDEALE > 230 AND TEMPERATURA_IDEALE < 330) --TRA -43°C E 57°C
);









--CREAZIONE ANIMALE

CREATE TABLE ANIMALE (
    ETICHETTA CHAR(10),
    DATA_USCITA DATE,
    ETICHETTA_GENITORE CHAR(10),
    SESSO CHAR(1) 
        CONSTRAINT NN_ANIMALE_SESSO NOT NULL,
    MESE_NASCITA NUMBER(2,0) 
        CONSTRAINT NN_ANIMALE_MESE_NASCITA NOT NULL,
    ANNO_NASCITA NUMBER(4,0) 
        CONSTRAINT NN_ANIMALE_ANNO_NASCITA NOT NULL,
    DATA_INGRESSO DATE 
        CONSTRAINT NN_ANIMALE_DATA_INGRESSO NOT NULL,
    NOME_TIPO_ANIMALE VARCHAR2(30) 
        CONSTRAINT NN_ANIMALE_FK_TIPO_ANIMALE NOT NULL,

    --PK
    CONSTRAINT PK_ANIMALE PRIMARY KEY (ETICHETTA),

    --FK
    CONSTRAINT FK_ANIMALE_TIPO_ANIMALE 
        FOREIGN KEY (NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE),

    CONSTRAINT FK_ANIMALE_GENITORE
        FOREIGN KEY (ETICHETTA_GENITORE)
        REFERENCES ANIMALE (ETICHETTA),
    
    --CHECK
    CONSTRAINT CK_ANIMALE_SESSO 
        CHECK (SESSO IN ('M', 'F', 'O')),

    CONSTRAINT CK_ANIMALE_ANNO_NASCITA 
        CHECK (ANNO_NASCITA >= 1900),
    
    CONSTRAINT CK_ANIMALE_MESE_NASCITA
        CHECK (MESE_NASCITA >= 1 AND MESE_NASCITA <= 12),

    CONSTRAINT CK_ANIMALE_DATA_INGRESSO
        CHECK (DATA_INGRESSO >= DATE '2026-01-01'),
    
    CONSTRAINT CK_ANIMALE_DATA_USCITA
        CHECK (DATA_USCITA IS NULL OR DATA_USCITA >= DATA_INGRESSO)
);




--CREAZIONE STADIO_CRESCITA

CREATE TABLE STADIO_CRESCITA (
    NOME_STADIO_CRESCITA VARCHAR2(30), 
    NOME_TIPO_ANIMALE VARCHAR2(30),
    LIVELLO_BIOSICUREZZA_MINIMO VARCHAR2(15)
        CONSTRAINT NN_STADIO_CRESCITA_LIVELLO_BIOSICUREZZA_MINIMO NOT NULL,
    ETA_MINIMA_MESI NUMBER(4,0)
        CONSTRAINT NN_STADIO_CRESCITA_ETA_MINIMA NOT NULL,
    
    
    --PK
    CONSTRAINT PK_STADIO_CRESCITA PRIMARY KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --FK
    CONSTRAINT FK_STADIO_CRESCITA_TIPO_ANIMALE
        FOREIGN KEY (NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE),
    
    --CHECK
    CONSTRAINT CK_STADIO_CRESCITA_LIVELLO_BIOSICUREZZA_MINIMO
        CHECK (LIVELLO_BIOSICUREZZA_MINIMO IN (
                'BASSO',
                'MEDIO',
                'ALTO'
            )),

    CONSTRAINT CK_STADIO_CRESCITA_ETA_MINIMA
        CHECK (ETA_MINIMA_MESI >= 0)
);




--CREAZIONE TABELLA ASSOCIATIVA STADIO_CRESCITA COLLEGAMENTO A DIETA

CREATE TABLE STADIO_CRESCITA_PREVEDE_DIETA (
    
)