--NOME_FARMACO, ETICHETTA_ANIMALE, DATA_VISITA, NOME_PRODOTTO, UNITA_MISURA, DURATA_GIORNI, QUANTITA_GIORNALIERA
INSERT INTO PRESCRIZIONE_ANIMALE VALUES ('Integratore ingresso bovino', '0000000001', DATE '2025-02-26', 'Integratore vitaminico veterinario', 'mL', 5, 20.0);
INSERT INTO PRESCRIZIONE_ANIMALE VALUES ('Terapia pollame biosicurezza', '0000000036', DATE '2025-03-10', 'Antibiotico veterinario pollame', 'mL', 7, 0.5);

COMMIT;