CREATE TABLE VACCINAZIONE(
    ETICHETTA_ANIMALE CHAR(10),
    NOME_VACCINO VARCHAR(60),
    NOME_TIPO_ANIMALE VARCHAR(60),
    NOME_STADIO_CRESCITA VARCHAR(60),
    DATA_VACCINAZIONE DATE,
    
    --PK
    CONSTRAINT PK_VACCINAZIONE
        PRIMARY KEY(
            ETICHETTA_ANIMALE, 
            NOME_VACCINO, 
            NOME_TIPO_ANIMALE, 
            NOME_STADIO_CRESCITA, 
            DATA_VACCINAZIONE
        ),

    --FK
    CONSTRAINT FK_VACCINAZIONE_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),
    
    CONSTRAINT FK_VACCINAZIONE_VACCINO
        FOREIGN KEY (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA)
        REFERENCES VACCINO (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA)
);