--CODICE_CELLA_IDR, CODICE_AREA, NOME_STRUTTURA, NOME_MOD_COLTIVAZIONE
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000A', 'A00A', 'Struttura Agricola', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000A', 'A00A', 'Struttura Agricola', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000A', 'A00A', 'Struttura Agricola', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000B', 'A00A', 'Struttura Agricola', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000B', 'A00A', 'Struttura Agricola', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000C', 'A00B', 'Struttura Agricola', 'Idro pomodoro intensivo');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000C', 'A00B', 'Struttura Agricola', 'Idro pomodoro standard');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000C', 'A00B', 'Struttura Agricola', 'Idro cucurbitacee');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000D', 'A00C', 'Struttura Agricola', 'Idro pomodoro standard');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000D', 'A00C', 'Struttura Agricola', 'Idro cucurbitacee');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000D', 'A00C', 'Struttura Agricola', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001A', 'A00A', 'Struttura Agricola II', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001A', 'A00A', 'Struttura Agricola II', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001A', 'A00A', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001A', 'A00A', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001B', 'A00A', 'Struttura Agricola II', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001B', 'A00A', 'Struttura Agricola II', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001B', 'A00A', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001B', 'A00A', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001C', 'A00A', 'Struttura Agricola II', 'Idro pomodoro standard');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001C', 'A00A', 'Struttura Agricola II', 'Idro cucurbitacee');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001C', 'A00A', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001C', 'A00A', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002A', 'A00B', 'Struttura Agricola II', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002A', 'A00B', 'Struttura Agricola II', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002A', 'A00B', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002A', 'A00B', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002B', 'A00B', 'Struttura Agricola II', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002B', 'A00B', 'Struttura Agricola II', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002B', 'A00B', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002B', 'A00B', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002C', 'A00B', 'Struttura Agricola II', 'Idro pomodoro intensivo');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002C', 'A00B', 'Struttura Agricola II', 'Idro pomodoro standard');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002C', 'A00B', 'Struttura Agricola II', 'Idro cucurbitacee');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002C', 'A00B', 'Struttura Agricola II', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002D', 'A00B', 'Struttura Agricola II', 'Idro pomodoro standard');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002D', 'A00B', 'Struttura Agricola II', 'Idro cucurbitacee');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002D', 'A00B', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002D', 'A00B', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002E', 'A00B', 'Struttura Agricola II', 'Idro cereali base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002E', 'A00B', 'Struttura Agricola II', 'Idro lattuga rapida');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002E', 'A00B', 'Struttura Agricola II', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002E', 'A00B', 'Struttura Agricola II', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('002E', 'A00B', 'Struttura Agricola II', 'Idro cucurbitacee');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000A', 'A00A', 'Struttura Agricola', 'Idro pomodoro standard');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000B', 'A00A', 'Struttura Agricola', 'Idro soia nutriente');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000C', 'A00B', 'Struttura Agricola', 'Idro legumi base');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000D', 'A00C', 'Struttura Agricola', 'Idro tuberi substrato');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('000D', 'A00C', 'Struttura Agricola', 'Idro radici substrato');
INSERT INTO CELLA_IDR_RISPETTA_MOD_COLT VALUES ('001C', 'A00A', 'Struttura Agricola II', 'Idro tuberi substrato');

