--NOME_TIPO_COLTURA, NOME_MODALITA_COLTIVAZIONE
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Grano duro', 'Idro cereali base');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Mais', 'Idro cereali base');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Pomodoro', 'Idro pomodoro standard');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Pomodoro', 'Idro pomodoro intensivo');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Lattuga', 'Idro lattuga rapida');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Zucchina', 'Idro cucurbitacee');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Fagiolo', 'Idro legumi base');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Soia', 'Idro soia nutriente');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Soia', 'Idro legumi base');
