import os
import sys
import json

dir = os.getcwd()
while os.path.basename(dir) != "MilkWayFarm":
    os.chdir("..")
    dir = os.getcwd()

sys.path.append(dir)

from make_DML.core.utils.make_DML_line import make_DML_line
from make_DML.core.utils.make_DML import make_DML


#MODALITA_COLTIVAZIONE:NOME_MODALITA_COLTIVAZIONE NOME_PRODOTTO PH_MIN PH_MAX TEMPERATURA_MIN TEMPERATURA_MAX UMIDITA_MIN UMIDITA_MAX IMPOLLINAZIONE SISTEMA_ILLUMINAZIONE ACQUA_ML_ORA ORE_LUCE_GIORNO SOLUZIONE_NUTRITIVA QUANTITA_SOLUZIONE_ML_ORA 

NOME_MODALITA_COLTIVAZIONE = []

NOME_PRODOTTO = []

PH_MIN = []

PH_MAX = []

TEMPERATURA_MIN = []

TEMPERATURA_MAX = []

UMIDITA_MIN = []

UMIDITA_MAX = []

IMPOLLINAZIONE = []

SISTEMA_ILLUMINAZIONE = []

ACQUA_ML_ORA = []

ORE_LUCE_GIORNO = []

SOLUZIONE_NUTRITIVA = []

QUANTITA_SOLUZIONE_ML_ORA = []


theList=list(zip(NOME_MODALITA_COLTIVAZIONE, NOME_PRODOTTO, PH_MIN, PH_MAX, TEMPERATURA_MIN, TEMPERATURA_MAX, UMIDITA_MIN, UMIDITA_MAX, IMPOLLINAZIONE, SISTEMA_ILLUMINAZIONE, ACQUA_ML_ORA, ORE_LUCE_GIORNO, SOLUZIONE_NUTRITIVA, QUANTITA_SOLUZIONE_ML_ORA))

keys = ["NOME_MODALITA_COLTIVAZIONE", "NOME_PRODOTTO", "PH_MIN", "PH_MAX", "TEMPERATURA_MIN", "TEMPERATURA_MAX", "UMIDITA_MIN", "UMIDITA_MAX", "IMPOLLINAZIONE", "SISTEMA_ILLUMINAZIONE", "ACQUA_ML_ORA", "ORE_LUCE_GIORNO", "SOLUZIONE_NUTRITIVA", "QUANTITA_SOLUZIONE_ML_ORA"]

theJsonList=[dict(zip(keys, row)) for row in theList]

lines="--NOME_MODALITA_COLTIVAZIONE, NOME_PRODOTTO, PH_MIN, PH_MAX, TEMPERATURA_MIN, TEMPERATURA_MAX, UMIDITA_MIN, UMIDITA_MAX, IMPOLLINAZIONE, SISTEMA_ILLUMINAZIONE, ACQUA_ML_ORA, ORE_LUCE_GIORNO, SOLUZIONE_NUTRITIVA, QUANTITA_SOLUZIONE_ML_ORA\n"
for i in range(len(theList)):
  lines+=make_DML_line("MODALITA_COLTIVAZIONE", theList[i])+"\n"

os.makedirs("make_DML/data/4_agricoltura", exist_ok=True)
with open("make_DML/data/4_agricoltura/1_modalita_coltivazione.json", "w", encoding="utf-8") as f:
   json.dump(theJsonList, f, indent=4, ensure_ascii=False)

make_DML("DB/DML/4_agricoltura/1_modalita_coltivazione.sql", lines)