CREATE TABLE MISSIONE_RIFORNIMENTO(
    NOME_MISSIONE VARCHAR(60),
    DATA_LANCIO DATE
        CONSTRAINT NN_MISSIONE_RIFORNIMENTO_DATA_LANCIO NOT NULL,
    DATA_ARRIVO_PREVISTO DATE
        CONSTRAINT NN_MISSIONE_RIFORNIMENTO_DATA_ARRIVO_PREVISTO NOT NULL,
    DATA_ARRIVO_EFFETTIVO DATE
        CONSTRAINT NN_MISSIONE_RIFORNIMENTO_DATA_ARRIVO_EFFETTIVO NOT NULL,
    VOLUME_RIFORNIMENTO_M3 NUMBER(10,2)
        CONSTRAINT NN_MISSIONE_RIFORNIMENTO_VOLUME_RIFORNIMENTO_M3 NOT NULL,
    MASSA_RIFORNIMENTO_KG NUMBER(10,2)
        CONSTRAINT NN_MISSIONE_RIFORNIMENTO_MASSA_RIFORNIMENTO_KG NOT NULL,
    BASE_PARTENZA VARCHAR(60)
        CONSTRAINT NN_MISSIONE_RIFORNIMENTO_BASE_PARTENZA NOT NULL,

    --PK
    CONSTRAINT PK_MISSIONE_RIFORNIMENTO 
        PRIMARY KEY (NOME_MISSIONE),
    
    --CHECK
    CONSTRAINT CK_VOLUME_RIFORNIMENTO_M3
        CHECK (VOLUME_RIFORNIMENTO_M3 > 0),
    
    CONSTRAINT CK_MASSA_RIFORNIMENTO_KG
        CHECK (MASSA_RIFORNIMENTO_KG > 0)
);