CREATE TABLE PRODOTTO_MISSIONE(
    NOME_PRODOTTO VARCHAR(60),
    NOME_MISSIONE VARCHAR(60),
    QUANTITA NUMBER(10,2) 
        CONSTRAINT NN_PRODOTTO_MISSIONE_QUANTITA NOT NULL,
    DATA_PRODUZIONE DATE
        CONSTRAINT NN_PRODOTTO_MISSIONE_DATA_PRODUZIONE NOT NULL,

    --PK
    CONSTRAINT PK_PRODOTTO_MISSIONE
        PRIMARY KEY (NOME_PRODOTTO, NOME_MISSIONE),
    
    --FK
    CONSTRAINT FK_PRODOTTO_MISSIONE_TIPO_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    CONSTRAINT FK_PRODOTTO_MISSIONE_MISSIONE_RIFORNIMENTO
        FOREIGN KEY (NOME_MISSIONE)
        REFERENCES MISSIONE_RIFORNIMENTO (NOME_MISSIONE)
);