--NOME_TIPO_ANIMALE, SPECIE, VITA_MEDIA_ANNI, MODALITA_RIPRODUZIONE, GIORNI_GESTAZIONE, UMIDITA_IDEALE, SPAZIO_MINIMO_MQ, TEMPERATURA_IDEALE
INSERT INTO TIPO_ANIMALE VALUES ('Gallina', 'Gallus gallus domesticus', 6.0, 'OVIPARA', 21, 55, 0.3, 294);
INSERT INTO TIPO_ANIMALE VALUES ('Coniglio', 'Oryctolagus cuniculus', 8.0, 'VIVIPARA', 31, 50, 0.7, 291);
INSERT INTO TIPO_ANIMALE VALUES ('Capra', 'Capra hircus', 12.0, 'VIVIPARA', 150, 55, 3.0, 290);
INSERT INTO TIPO_ANIMALE VALUES ('Pecora', 'Ovis aries', 12.0, 'VIVIPARA', 147, 55, 2.5, 290);
INSERT INTO TIPO_ANIMALE VALUES ('Maiale', 'Sus scrofa domesticus', 10.0, 'VIVIPARA', 114, 60, 2.0, 293);
INSERT INTO TIPO_ANIMALE VALUES ('Bovino', 'Bos taurus', 15.0, 'VIVIPARA', 283, 55, 8.0, 289);
INSERT INTO TIPO_ANIMALE VALUES ('Tacchino', 'Meleagris gallopavo', 6.0, 'OVIPARA', 28, 55, 0.8, 294);

COMMIT;