--NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, LIVELLO_BIOSICUREZZA_MINIMO, ETA_MINIMA_MESI
INSERT INTO STADIO_CRESCITA VALUES ('Pulcino', 'Gallina', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Gallina', 'MEDIO', 1);
INSERT INTO STADIO_CRESCITA VALUES ('Ovodeposizione', 'Gallina', 'MEDIO', 5);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Gallina', 'BASSO', 12);
INSERT INTO STADIO_CRESCITA VALUES ('Cucciolo', 'Coniglio', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Svezzamento', 'Coniglio', 'ALTO', 1);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Coniglio', 'MEDIO', 2);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Coniglio', 'BASSO', 5);
INSERT INTO STADIO_CRESCITA VALUES ('Capretto', 'Capra', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Svezzamento', 'Capra', 'MEDIO', 3);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Capra', 'MEDIO', 6);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Capra', 'BASSO', 12);
INSERT INTO STADIO_CRESCITA VALUES ('Agnello', 'Pecora', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Svezzamento', 'Pecora', 'MEDIO', 3);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Pecora', 'MEDIO', 6);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Pecora', 'BASSO', 12);
INSERT INTO STADIO_CRESCITA VALUES ('Suinetto', 'Maiale', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Svezzamento', 'Maiale', 'ALTO', 1);
INSERT INTO STADIO_CRESCITA VALUES ('Accrescimento', 'Maiale', 'MEDIO', 3);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Maiale', 'BASSO', 8);
INSERT INTO STADIO_CRESCITA VALUES ('Vitello', 'Bovino', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Svezzamento', 'Bovino', 'MEDIO', 3);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Bovino', 'MEDIO', 12);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Bovino', 'BASSO', 24);
INSERT INTO STADIO_CRESCITA VALUES ('Pulcino', 'Tacchino', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Tacchino', 'MEDIO', 2);
INSERT INTO STADIO_CRESCITA VALUES ('Ingrasso', 'Tacchino', 'MEDIO', 4);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Tacchino', 'BASSO', 7);


COMMIT;