--NUMERO_SCAFFALE, CODICE_AREA, NOME_STRUTTURA, NOME_CONSERVAZIONE
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00A', 'Primo Modulo', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00A', 'Primo Modulo', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00B', 'Primo Modulo', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00B', 'Primo Modulo', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00A', 'Struttura Agricola', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00A', 'Struttura Agricola', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00A', 'Struttura Stoccaggio', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00A', 'Struttura Stoccaggio', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00A', 'Struttura Stoccaggio', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00A', 'Struttura Stoccaggio', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00A', 'Struttura Stoccaggio', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00A', 'Struttura Stoccaggio', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0004', 'A00A', 'Struttura Stoccaggio', 'Ambiente secco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0004', 'A00A', 'Struttura Stoccaggio', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00B', 'Struttura Stoccaggio', 'Ambiente fresco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00B', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00B', 'Struttura Stoccaggio', 'Ambiente fresco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00B', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00B', 'Struttura Stoccaggio', 'Ambiente fresco controllato');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00B', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00C', 'Struttura Stoccaggio', 'Refrigerazione standard');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00C', 'Struttura Stoccaggio', 'Refrigerazione standard');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00C', 'Struttura Stoccaggio', 'Refrigerazione standard');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00D', 'Struttura Stoccaggio', 'Congelamento standard');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00D', 'Struttura Stoccaggio', 'Congelamento standard');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00D', 'Struttura Stoccaggio', 'Congelamento standard');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00E', 'Struttura Stoccaggio', 'Catena del freddo sanitaria');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00E', 'Struttura Stoccaggio', 'Catena del freddo sanitaria');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00F', 'Struttura Stoccaggio', 'Conservazione semi breve termine');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00F', 'Struttura Stoccaggio', 'Conservazione semi breve termine');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00G', 'Struttura Stoccaggio', 'Conservazione semi lungo termine');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00G', 'Struttura Stoccaggio', 'Conservazione semi lungo termine');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00H', 'Struttura Stoccaggio', 'Conservazione tuberi e radici');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00H', 'Struttura Stoccaggio', 'Conservazione tuberi e radici');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00H', 'Struttura Stoccaggio', 'Conservazione tuberi e radici');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00I', 'Struttura Stoccaggio', 'Conservazione verdure fresche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00I', 'Struttura Stoccaggio', 'Conservazione verdure fresche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00J', 'Struttura Stoccaggio', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00J', 'Struttura Stoccaggio', 'Conservazione mangimi secchi');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00K', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00K', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00K', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0004', 'A00K', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00L', 'Struttura Stoccaggio', 'Conservazione soluzioni agricole');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0001', 'A00L', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00L', 'Struttura Stoccaggio', 'Conservazione soluzioni agricole');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0002', 'A00L', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00L', 'Struttura Stoccaggio', 'Conservazione soluzioni agricole');
INSERT INTO SCAFFALE_RISPETTA_MOD_CONS VALUES ('0003', 'A00L', 'Struttura Stoccaggio', 'Conservazione biomasse organiche');
