--NOME_PRODOTTO, NOME_DIETA, QUANTITA
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Pulcino', 0.25);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ingrasso', 'Dieta Gallina Pulcino', 0.035);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Giovane', 0.35);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ingrasso', 'Dieta Gallina Giovane', 0.07);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Giovane', 0.015);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Uova', 0.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ovaiole', 'Dieta Gallina Uova', 0.12);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Uova', 0.02);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Gallina Uova', 0.002);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Adulta', 0.45);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ovaiole', 'Dieta Gallina Adulta', 0.1);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Adulta', 0.015);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Cucciolo', 0.15);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime conigli', 'Dieta Coniglio Cucciolo', 0.03);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Coniglio Cucciolo', 0.02);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Svezz', 0.3);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime conigli', 'Dieta Coniglio Svezz', 0.06);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Coniglio Svezz', 0.08);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Carota', 'Dieta Coniglio Svezz', 0.02);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Giovane', 0.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime conigli', 'Dieta Coniglio Giovane', 0.09);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Coniglio Giovane', 0.15);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Coniglio Giovane', 0.03);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Adulto', 0.7);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime conigli', 'Dieta Coniglio Adulto', 0.12);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Coniglio Adulto', 0.25);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Carota', 'Dieta Coniglio Adulto', 0.04);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Capretto', 1.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Capra Capretto', 0.25);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Capra Capretto', 0.3);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Svezz', 2.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Capra Svezz', 0.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Capra Svezz', 0.8);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Capra Svezz', 0.008);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Giovane', 4.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Capra Giovane', 0.8);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Capra Giovane', 1.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Capra Giovane', 0.012);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Adulta', 6.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Capra Adulta', 1.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Capra Adulta', 2.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Capra Adulta', 0.018);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Pecora Agnello', 1.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Pecora Agnello', 0.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Pecora Agnello', 0.25);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Pecora Svezz', 2.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Pecora Svezz', 0.45);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Pecora Svezz', 0.7);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Pecora Svezz', 0.007);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Pecora Giovane', 3.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Pecora Giovane', 0.7);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Pecora Giovane', 1.3);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Pecora Giovane', 0.01);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Pecora Adulta', 5.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime ovicaprini', 'Dieta Pecora Adulta', 0.9);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Pecora Adulta', 2.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Pecora Adulta', 0.015);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Maiale Suinetto', 1.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime suini', 'Dieta Maiale Suinetto', 0.4);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Maiale Suinetto', 0.1);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Maiale Svezz', 2.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime suini', 'Dieta Maiale Svezz', 0.9);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Maiale Svezz', 0.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Maiale Svezz', 0.08);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Maiale Ingrasso', 6.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime suini', 'Dieta Maiale Ingrasso', 2.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Maiale Ingrasso', 0.6);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Maiale Ingrasso', 0.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Maiale Adulto', 5.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime suini', 'Dieta Maiale Adulto', 1.8);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Maiale Adulto', 0.4);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Maiale Adulto', 0.15);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Vitello', 8.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime bovini crescita', 'Dieta Bovino Vitello', 1.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Bovino Vitello', 2.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Bovino Vitello', 0.02);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Svezz', 15.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime bovini crescita', 'Dieta Bovino Svezz', 2.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Bovino Svezz', 5.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Bovino Svezz', 0.035);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Giovane', 25.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime bovini crescita', 'Dieta Bovino Giovane', 4.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Bovino Giovane', 9.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Bovino Giovane', 0.05);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Adulto', 40.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime bovini lattazione', 'Dieta Bovino Adulto', 5.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Fieno essiccato', 'Dieta Bovino Adulto', 12.0);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Sale minerale zootecnico', 'Dieta Bovino Adulto', 0.08);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Tacchino Pulcino', 0.3);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ingrasso', 'Dieta Tacchino Pulcino', 0.05);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Tacchino Giovane', 0.8);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ingrasso', 'Dieta Tacchino Giovane', 0.16);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Tacchino Giovane', 0.03);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Tacchino Ingrasso', 1.5);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ingrasso', 'Dieta Tacchino Ingrasso', 0.35);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Tacchino Ingrasso', 0.08);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Tacchino Adulto', 1.2);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mangime pollame ingrasso', 'Dieta Tacchino Adulto', 0.25);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Tacchino Adulto', 0.06);
