--NOME_CONSERVAZIONE, NOME_PRODOTTO
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Latte bovino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Latte bovino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Latte caprino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Latte caprino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Latte ovino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Latte ovino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Formaggio fresco');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Yogurt naturale');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Burro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Burro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Panna');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Panna');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Uova di gallina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Uova di quaglia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne bovina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne bovina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne suina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne suina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne ovina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne ovina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne caprina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne caprina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne di pollo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne di pollo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne di tacchino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne di tacchino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Carne di coniglio');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Congelamento standard', 'Carne di coniglio');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Grano duro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Grano duro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Farina di grano');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Farina di grano');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mais');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Mais');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Fagiolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Fagiolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Ceci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Ceci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Lenticchie');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Lenticchie');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Piselli');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Piselli');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Soia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Soia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione tuberi e radici', 'Patata');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Patata');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione tuberi e radici', 'Carota');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Carota');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Pomodoro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Pomodoro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Lattuga');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Lattuga');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Spinaci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Spinaci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Zucchina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Zucchina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Cetriolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Cetriolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Melanzana');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Melanzana');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Peperone');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Peperone');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Fragola');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Fragola');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Mela');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Mela');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Pera');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Pera');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Uva');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Uva');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione verdure fresche', 'Funghi coltivati');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Funghi coltivati');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Alghe alimentari');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Alghe alimentari');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di grano duro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di grano duro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di mais');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di mais');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di pomodoro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di pomodoro');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di lattuga');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di lattuga');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di spinaci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di spinaci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di carota');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di carota');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di zucchina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di zucchina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di cetriolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di cetriolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di peperone');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di peperone');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di fagiolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di fagiolo');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di ceci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di ceci');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di lenticchie');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di lenticchie');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Semi di soia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Semi di soia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Spore di funghi coltivati');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi lungo termine', 'Spore di funghi coltivati');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione tuberi e radici', 'Talee di patata');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione semi breve termine', 'Talee di patata');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione soluzioni agricole', 'Soluzione nutritiva idroponica base');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Soluzione nutritiva idroponica base');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione soluzioni agricole', 'Soluzione nutritiva concentrata');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Soluzione nutritiva concentrata');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione soluzioni agricole', 'Correttore pH acido');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Correttore pH acido');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione soluzioni agricole', 'Correttore pH basico');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Correttore pH basico');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Lana di roccia agricola');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione biomasse organiche', 'Compost sterile');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Compost sterile');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione soluzioni agricole', 'Biofertilizzante microbico');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Biofertilizzante microbico');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Fieno essiccato');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Fieno essiccato');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Paglia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Paglia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime bovini crescita');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime bovini crescita');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime bovini lattazione');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime bovini lattazione');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime ovicaprini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime ovicaprini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime suini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime suini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime pollame ovaiole');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime pollame ovaiole');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime pollame ingrasso');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime pollame ingrasso');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Mangime conigli');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Mangime conigli');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione mangimi secchi', 'Sale minerale zootecnico');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Sale minerale zootecnico');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antibiotico veterinario bovini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antibiotico veterinario bovini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antibiotico veterinario suini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antibiotico veterinario suini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antibiotico veterinario pollame');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antibiotico veterinario pollame');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antiparassitario bovini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antiparassitario bovini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antiparassitario ovicaprini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antiparassitario ovicaprini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antiparassitario suini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antiparassitario suini');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antiparassitario pollame');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antiparassitario pollame');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Antinfiammatorio veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Antinfiammatorio veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Disinfettante ferite animali');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Disinfettante ferite animali');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Integratore vitaminico veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Integratore vitaminico veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Reidratante orale veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Reidratante orale veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Probiotico veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Refrigerazione standard', 'Probiotico veterinario');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Pomata cicatrizzante veterinaria');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Pomata cicatrizzante veterinaria');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino bovini respiratorio');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino bovini clostridiosi');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino bovini mastite');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino ovicaprini clostridiosi');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino ovicaprini enterotossiemia');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino suini parvovirosi');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino suini mal rosso');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino pollame Newcastle');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino pollame bronchite infettiva');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino pollame coccidiosi');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino conigli mixomatosi');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Catena del freddo sanitaria', 'Vaccino conigli malattia emorragica');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Lana ovina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Pelle bovina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione biomasse organiche', 'Letame bovino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione biomasse organiche', 'Letame ovino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione biomasse organiche', 'Letame suino');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione biomasse organiche', 'Pollina');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente secco controllato', 'Piume di pollame');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Ambiente fresco controllato', 'Acqua potabile');
INSERT INTO PRODOTTO_PREVEDE_MOD_CONS VALUES ('Conservazione soluzioni agricole', 'Acqua potabile');
