CREATE TABLE SCAFFALE_RISPETTA_MOD_CONS(
    NUMERO_SCAFFALE CHAR(4),
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    NOME_CONSERVAZIONE VARCHAR(60),

    --PK
    CONSTRAINT PK_SCAFFALE_RISPETTA_MOD_CONS
        PRIMARY KEY (NUMERO_SCAFFALE, CODICE_AREA, NOME_STRUTTURA, NOME_CONSERVAZIONE),

    --FK
    CONSTRAINT FK_SCAFFALE_RISPETTA_MOD_CONS_SCAFFALE
        FOREIGN KEY (NUMERO_SCAFFALE, CODICE_AREA, NOME_STRUTTURA)
        REFERENCES SCAFFALE (NUMERO_SCAFFALE, CODICE_AREA, NOME_STRUTTURA),
    
    CONSTRAINT FK_SCAFFALE_RISPETTA_MOD_CONS_MODALITA_CONSERVAZIONE
        FOREIGN KEY (NOME_CONSERVAZIONE)
        REFERENCES MODALITA_CONSERVAZIONE (NOME_CONSERVAZIONE)
);