CREATE TABLE SERB_RISPETTA_MOD_CONS(
    NUMERO_SERBATOIO CHAR(4),
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    NOME_CONSERVAZIONE VARCHAR2(30),

    --PK
    CONSTRAINT PK_SERB_RISPETTA_MOD_CONS
        PRIMARY KEY (NUMERO_SERBATOIO, CODICE_AREA, NOME_STRUTTURA, NOME_CONSERVAZIONE),

    --FK
    CONSTRAINT FK_SERB_RISPETTA_MOD_CONS_SERBATOIO
        FOREIGN KEY (NUMERO_SERBATOIO, CODICE_AREA, NOME_STRUTTURA)
        REFERENCES SERBATOIO (NUMERO_SERBATOIO, CODICE_AREA, NOME_STRUTTURA),
    
    CONSTRAINT FK_SERB_RISPETTA_MOD_CONS_MODALITA_CONSERVAZIONE
        FOREIGN KEY (NOME_CONSERVAZIONE)
        REFERENCES MODALITA_CONSERVAZIONE (NOME_CONSERVAZIONE)
);