CREATE TABLE PRODUZIONE_AGRICOLA_ALLOC_SERB(
    DATA_PRODUZIONE_AGRICOLA DATE,
    DATA_INIZIO_CICLO_COLTIVAZIONE DATE,
    CODICE_CELLA_IDR CHAR(4),
    CODICE_AREA_CELLA CHAR(4),
    NOME_STRUTTURA_CELLA VARCHAR2(30),
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SERBATOIO CHAR(4),
    CODICE_AREA_SERB CHAR(4),
    NOME_STRUTTURA_SERB VARCHAR2(30),
    QUANTITA_ALLOCATA NUMBER(10,2)
        CONSTRAINT NN_PRODUZIONE_AGRICOLA_ALLOC_SERB_QUANTITA_ALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_PRODUZIONE_AGRICOLA_ALLOC_SERB
        PRIMARY KEY (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA,
            NOME_PRODOTTO,
            NUMERO_SERBATOIO,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        ),
    
    --FK
    CONSTRAINT FK_PRODUZIONE_AGRICOLA_ALLOC_SERB_PRODUZIONE_AGRICOLA
        FOREIGN KEY (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA,
            NOME_PRODOTTO
        )
        REFERENCES PRODUZIONE_AGRICOLA (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA,
            NOME_PRODOTTO
        ),

    CONSTRAINT FK_PRODUZIONE_AGRICOLA_ALLOC_SERB_SERBATOIO
        FOREIGN KEY (
            NUMERO_SERBATOIO,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        )
        REFERENCES SERBATOIO (
            NUMERO_SERBATOIO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),
    
    --CHECK
    CONSTRAINT CK_PRODUZIONE_AGRICOLA_ALLOC_SERB_QUANTITA_ALLOCATA
        CHECK (QUANTITA_ALLOCATA > 0)
);