CREATE TABLE PRODUZIONE_AGRICOLA_ALLOC_SCAFF(
    DATA_PRODUZIONE_AGRICOLA DATE,
    DATA_INIZIO_CICLO_COLTIVAZIONE DATE,
    CODICE_CELLA_IDR CHAR(4),
    CODICE_AREA_CELLA CHAR(4),
    NOME_STRUTTURA_CELLA VARCHAR(60),
    NOME_PRODOTTO VARCHAR(60),
    NUMERO_SCAFFALE CHAR(4),
    CODICE_AREA_SCAFF CHAR(4),
    NOME_STRUTTURA_SCAFF VARCHAR(60),
    QUANTITA_ALLOCATA NUMBER(10,2)
        CONSTRAINT NN_PRODUZIONE_AGRICOLA_ALLOC_SCAFF_QUANTITA_ALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_PRODUZIONE_AGRICOLA_ALLOC_SCAFF
        PRIMARY KEY (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA,
            NOME_PRODOTTO,
            NUMERO_SCAFFALE,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF    
        ),
    
    --FK
    CONSTRAINT FK_PRODUZIONE_AGRICOLA_ALLOC_SCAFF_PRODUZIONE_AGRICOLA
        FOREIGN KEY (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA,
            NOME_PRODOTTO
        )
        REFERENCES PRODUZIONE_AGRICOLA (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA,
            NOME_PRODOTTO
        ),

    CONSTRAINT FK_PRODUZIONE_AGRICOLA_ALLOC_SCAFF_SCAFFALE
        FOREIGN KEY (
            NUMERO_SCAFFALE,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        )
        REFERENCES SCAFFALE (
            NUMERO_SCAFFALE,
            CODICE_AREA,
            NOME_STRUTTURA
        ),
    
    --CHECK
    CONSTRAINT CK_PRODUZIONE_AGRICOLA_ALLOC_SCAFF_QUANTITA_ALLOCATA
        CHECK (QUANTITA_ALLOCATA > 0)
);