CREATE TABLE PRODUZIONE_ANIMALE_ALLOC_SERB(
    DATA_PRODUZIONE DATE,
    NUMERO_BLOCCO CHAR(4),
    NOME_STRUTTURA_BLOCCO VARCHAR2(30),
    CODICE_AREA_BLOCCO CHAR(4),
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SERBATOIO CHAR(4),
    CODICE_AREA_SERB CHAR(4),
    NOME_STRUTTURA_SERB VARCHAR2(30),
    QUANTITA_ALLOCATA NUMBER(10,2)
        CONSTRAINT NN_PRODUZIONE_ANIMALE_ALLOC_SERB_QUANTITA_ALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_PRODUZIONE_ANIMALE_ALLOC_SERB
        PRIMARY KEY (
            DATA_PRODUZIONE,
            NUMERO_BLOCCO,
            NOME_STRUTTURA_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_PRODOTTO,
            NUMERO_SERBATOIO,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        ),

    --FK
    CONSTRAINT FK_PRODUZIONE_ANIMALE_ALLOC_SERB_PRODUZIONE_ANIMALE
        FOREIGN KEY (
            DATA_PRODUZIONE,
            NUMERO_BLOCCO,
            NOME_STRUTTURA_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_PRODOTTO
        )
        REFERENCES PRODUZIONE_ANIMALE (
            DATA_PRODUZIONE,
            NUMERO_BLOCCO,
            NOME_STRUTTURA,
            CODICE_AREA,
            NOME_PRODOTTO
        ),

    CONSTRAINT FK_PRODUZIONE_ANIMALE_ALLOC_SERB_SERBATOIO
        FOREIGN KEY (
            NUMERO_SERBATOIO,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        )
        REFERENCES SERBATOIO (
            NUMERO_SERBATOIO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    --CHECK
    CONSTRAINT CK_PRODUZIONE_ANIMALE_ALLOC_SERB_QUANTITA_ALLOCATA
        CHECK (QUANTITA_ALLOCATA > 0)
);