CREATE TABLE PRODUZIONE_ANIMALE_ALLOC_SCAFF(
    DATA_PRODUZIONE DATE,
    NUMERO_BLOCCO CHAR(4),
    NOME_STRUTTURA_BLOCCO VARCHAR2(30),
    CODICE_AREA_BLOCCO CHAR(4),
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SCAFFALE CHAR(4),
    CODICE_AREA_SCAFF CHAR(4),
    NOME_STRUTTURA_SCAFF VARCHAR2(30),
    QUANTITA_ALLOCATA NUMBER(10,2)
        CONSTRAINT NN_PRODUZIONE_ANIMALE_ALLOC_SCAFF_QUANTITA_ALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_PRODUZIONE_ANIMALE_ALLOC_SCAFF
        PRIMARY KEY (
            DATA_PRODUZIONE,
            NUMERO_BLOCCO,
            NOME_STRUTTURA_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_PRODOTTO,
            NUMERO_SCAFFALE,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        ),

    --FK
    CONSTRAINT FK_PRODUZIONE_ANIMALE_ALLOC_SCAFF_PRODUZIONE_ANIMALE
        FOREIGN KEY (
            DATA_PRODUZIONE,
            NUMERO_BLOCCO,
            NOME_STRUTTURA_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_PRODOTTO
        )
        REFERENCES PRODUZIONE_ANIMALE (
            DATA_PRODUZIONE,
            NUMERO_BLOCCO,
            NOME_STRUTTURA,
            CODICE_AREA,
            NOME_PRODOTTO
        ),

    CONSTRAINT FK_PRODUZIONE_ANIMALE_ALLOC_SCAFF_SCAFFALE
        FOREIGN KEY (
            NUMERO_SCAFFALE,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        )
        REFERENCES SCAFFALE (
            NUMERO_SCAFFALE,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    --CHECK
    CONSTRAINT CK_PRODUZIONE_ANIMALE_ALLOC_SCAFF_QUANTITA_ALLOCATA
        CHECK (QUANTITA_ALLOCATA > 0)
);