CREATE TABLE PRODOTTO_MISSIONE_ALLOC_SERB(
    NOME_PRODOTTO VARCHAR(60),
    NOME_MISSIONE VARCHAR(60),
    NUMERO_SERBATOIO CHAR(4),
    CODICE_AREA_SERB CHAR(4),
    NOME_STRUTTURA_SERB VARCHAR(60),
    QUANTITA_ALLOCATA NUMBER(10,2)
        CONSTRAINT NN_PRODOTTO_MISSIONE_ALLOC_SERB_QUANTITA_ALLOCATA NOT NULL,
    
    --PK
    CONSTRAINT PK_PRODOTTO_MISSIONE_ALLOC_SERB
        PRIMARY KEY (
            NOME_PRODOTTO,
            NOME_MISSIONE,
            NUMERO_SERBATOIO,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        ),
    
    --FK
    CONSTRAINT FK_PRODOTTO_MISSIONE_ALLOC_SERB_PRODOTTO_MISSIONE
        FOREIGN KEY (
            NOME_PRODOTTO,
            NOME_MISSIONE
        )
        REFERENCES PRODOTTO_MISSIONE (
            NOME_PRODOTTO,
            NOME_MISSIONE
        ),

    CONSTRAINT FK_PRODOTTO_MISSIONE_ALLOC_SERB_SERBATOIO
        FOREIGN KEY (
            NUMERO_SERBATOIO,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        )
        REFERENCES SERBATOIO (
            NUMERO_SERBATOIO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),
    
    --CHECK
    CONSTRAINT CK_PRODOTTO_MISSIONE_ALLOC_SERB_QUANTITA_ALLOCATA
        CHECK (QUANTITA_ALLOCATA > 0)
);