CREATE TABLE PRODOTTO_MISSIONE_ALLOC_SCAFF(
    NOME_PRODOTTO VARCHAR2(30),
    NOME_MISSIONE VARCHAR2(30),
    NUMERO_SCAFFALE CHAR(4),
    CODICE_AREA_SCAFF CHAR(4),
    NOME_STRUTTURA_SCAFF VARCHAR2(30),
    QUANTITA_ALLOCATA NUMBER(10,2)
        CONSTRAINT NN_PRODOTTO_MISSIONE_ALLOC_SCAFF_QUANTITA_ALLOCATA NOT NULL,
    
    --PK
    CONSTRAINT PK_PRODOTTO_MISSIONE_ALLOC_SCAFF
        PRIMARY KEY (
            NOME_PRODOTTO,
            NOME_MISSIONE,
            NUMERO_SCAFFALE,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        ),
    
    --FK
    CONSTRAINT FK_PRODOTTO_MISSIONE_ALLOC_SCAFF_PRODOTTO_MISSIONE
        FOREIGN KEY (
            NOME_PRODOTTO,
            NOME_MISSIONE
        )
        REFERENCES PRODOTTO_MISSIONE (
            NOME_PRODOTTO,
            NOME_MISSIONE
        ),

    CONSTRAINT FK_PRODOTTO_MISSIONE_ALLOC_SCAFF_SCAFFALE
        FOREIGN KEY (
            NUMERO_SCAFFALE,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        )
        REFERENCES SCAFFALE (
            NUMERO_SCAFFALE,
            CODICE_AREA,
            NOME_STRUTTURA
        ),
    
    --CHECK
    CONSTRAINT CK_PRODOTTO_MISSIONE_ALLOC_SCAFF_QUANTITA_ALLOCATA
        CHECK (QUANTITA_ALLOCATA > 0)
);