CREATE TABLE DEALLOC_PROD_CICLO_COLT_SERB(
    DATE_MIN DATE,
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SERB CHAR(4),
    CODICE_AREA_SERB CHAR(4),
    NOME_STRUTTURA_SERB VARCHAR2(30),
    DATA_INIZIO DATE,
    CODICE_CELLA_IDR CHAR(4),
    CODICE_AREA_CELLA CHAR(4),
    NOME_STRUTTURA_CELLA VARCHAR2(30),
    QUANTITA_DEALLOCATA NUMBER(10,2)
        CONSTRAINT NN_DEALLOC_PROD_CICLO_COLT_SERB_QUANTITA_DEALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_DEALLOC_PROD_CICLO_COLT_SERB
        PRIMARY KEY (
            DATE_MIN,
            NOME_PRODOTTO,
            NUMERO_SERB,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB,
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA
        ),
    
    --FK
    CONSTRAINT FK_DEALLOC_PROD_CICLO_COLT_SERB_CICLO_COLTIVAZIONE
        FOREIGN KEY (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA
        )
        REFERENCES CICLO_COLTIVAZIONE (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    CONSTRAINT FK_DEALLOC_PROD_CICLO_COLT_SERB_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    CONSTRAINT FK_DEALLOC_PROD_CICLO_COLT_SERB_SERBATOIO
        FOREIGN KEY (
            NUMERO_SERB,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        )
        REFERENCES SERBATOIO (
            NUMERO_SERBATOIO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    --CHECK
    CONSTRAINT CK_DEALLOC_PROD_CICLO_COLT_SERB_QUANTITA_DEALLOCATA
        CHECK (QUANTITA_DEALLOCATA > 0)
);
