CREATE TABLE DEALLOC_PROD_CICLO_COLT_SCAFF(
    DATE_MIN DATE,
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SCAFF CHAR(4),
    CODICE_AREA_SCAFF CHAR(4),
    NOME_STRUTTURA_SCAFF VARCHAR2(30),
    DATA_INIZIO DATE,
    CODICE_CELLA_IDR CHAR(4),
    CODICE_AREA_CELLA CHAR(4),
    NOME_STRUTTURA_CELLA VARCHAR2(30),
    QUANTITA_DEALLOCATA NUMBER(10,2)
        CONSTRAINT NN_DEALLOC_PROD_CICLO_COLT_SCAFF_QUANTITA_DEALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_DEALLOC_PROD_CICLO_COLT_SCAFF
        PRIMARY KEY (
            DATE_MIN,
            NOME_PRODOTTO,
            NUMERO_SCAFF,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF,
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA
        ),
    
    --FK
    CONSTRAINT FK_DEALLOC_PROD_CICLO_COLT_SCAFF_CICLO_COLTIVAZIONE
        FOREIGN KEY (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA_CELLA,
            NOME_STRUTTURA_CELLA
        )
        REFERENCES CICLO_COLTIVAZIONE (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    CONSTRAINT FK_DEALLOC_PROD_CICLO_COLT_SCAFF_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    CONSTRAINT FK_DEALLOC_PROD_CICLO_COLT_SCAFF_SCAFFALE
        FOREIGN KEY (
            NUMERO_SCAFF,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        )
        REFERENCES SCAFFALE (
            NUMERO_SCAFFALE,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    --CHECK
    CONSTRAINT CK_DEALLOC_PROD_CICLO_COLT_SCAFF_QUANTITA_DEALLOCATA
        CHECK (QUANTITA_DEALLOCATA > 0)
);
