CREATE TABLE DEALLOC_PROD_BLOCCO_ANIMALE_SERB(
    DATE_MIN DATE,
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SERB CHAR(4),
    CODICE_AREA_SERB CHAR(4),
    NOME_STRUTTURA_SERB VARCHAR2(30),
    NUMERO_BLOCCO CHAR(4),
    CODICE_AREA_BLOCCO CHAR(4),
    NOME_STRUTTURA_BLOCCO VARCHAR2(30),
    QUANTITA_DEALLOCATA NUMBER(10,2)
        CONSTRAINT NN_DEALLOC_PROD_BLOCCO_ANIMALE_SERB_QUANTITA_DEALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_DEALLOC_PROD_BLOCCO_ANIMALE_SERB
        PRIMARY KEY (
            DATE_MIN,
            NOME_PRODOTTO,
            NUMERO_SERB,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB,
            NUMERO_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_STRUTTURA_BLOCCO   
        ),
    
    --FK
    CONSTRAINT FK_DEALLOC_PROD_BLOCCO_ANIMALE_SERB_BLOCCO_ANIMALE
        FOREIGN KEY (
            NUMERO_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_STRUTTURA_BLOCCO
        )
        REFERENCES BLOCCO_ANIMALE (
            NUMERO_BLOCCO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    CONSTRAINT FK_DEALLOC_PROD_BLOCCO_ANIMALE_SERB_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    CONSTRAINT FK_DEALLOC_PROD_BLOCCO_ANIMALE_SERB_SERBATOIO
        FOREIGN KEY (
            NUMERO_SERB,
            CODICE_AREA_SERB,
            NOME_STRUTTURA_SERB
        )
        REFERENCES SERBATOIO (
            NUMERO_SERBATOIO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    --CHECK
    CONSTRAINT CK_DEALLOC_PROD_BLOCCO_ANIMALE_SERB_QUANTITA_DEALLOCATA
        CHECK (QUANTITA_DEALLOCATA > 0)
);
