CREATE TABLE DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF(
    DATE_MIN DATE,
    NOME_PRODOTTO VARCHAR2(30),
    NUMERO_SCAFF CHAR(4),
    CODICE_AREA_SCAFF CHAR(4),
    NOME_STRUTTURA_SCAFF VARCHAR2(30),
    NUMERO_BLOCCO CHAR(4),
    CODICE_AREA_BLOCCO CHAR(4),
    NOME_STRUTTURA_BLOCCO VARCHAR2(30),
    QUANTITA_DEALLOCATA NUMBER(10,2)
        CONSTRAINT NN_DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF_QUANTITA_DEALLOCATA NOT NULL,

    --PK
    CONSTRAINT PK_DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF
        PRIMARY KEY (
            DATE_MIN,
            NOME_PRODOTTO,
            NUMERO_SCAFF,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF,
            NUMERO_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_STRUTTURA_BLOCCO   
        ),
    
    --FK
    CONSTRAINT FK_DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF_BLOCCO_ANIMALE
        FOREIGN KEY (
            NUMERO_BLOCCO,
            CODICE_AREA_BLOCCO,
            NOME_STRUTTURA_BLOCCO
        )
        REFERENCES BLOCCO_ANIMALE (
            NUMERO_BLOCCO,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    CONSTRAINT FK_DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    CONSTRAINT FK_DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF_SCAFFALE
        FOREIGN KEY (
            NUMERO_SCAFF,
            CODICE_AREA_SCAFF,
            NOME_STRUTTURA_SCAFF
        )
        REFERENCES SCAFFALE (
            NUMERO_SCAFFALE,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    --CHECK
    CONSTRAINT CK_DEALLOC_PROD_BLOCCO_ANIMALE_SCAFF_QUANTITA_DEALLOCATA
        CHECK (QUANTITA_DEALLOCATA > 0)
);
