CREATE TABLE PRODOTTO_PREVEDE_MOD_CONS(
    NOME_CONSERVAZIONE VARCHAR(60),
    NOME_PRODOTTO VARCHAR(60),

    --PK
    CONSTRAINT PK_PPMC
        PRIMARY KEY (NOME_PRODOTTO, NOME_CONSERVAZIONE),

    --FK 
    CONSTRAINT FK_PPMC_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    CONSTRAINT FK_PPMC_MOD_CONS
        FOREIGN KEY (NOME_CONSERVAZIONE)
        REFERENCES MODALITA_CONSERVAZIONE (NOME_CONSERVAZIONE)
);