SELECT distinct s.NOME_STADIO_CRESCITA, s.NOME_TIPO_ANIMALE FROM STADIO_CRESCITA s 
join STADIO_CRESCITA_PREVEDE_DIETA sa 
on s.NOME_STADIO_CRESCITA = sa.NOME_STADIO_CRESCITA and s.NOME_TIPO_ANIMALE= sa.NOME_TIPO_ANIMALE