CREATE TABLE REGISTRAZIONE_SENSORE(
    SERIALE VARCHAR(60),
    DATA_SECONDI DATE,
    NOME_PRODUTTORE VARCHAR(60),
    MISURAZIONE NUMBER(32,16),

    --PK 
    CONSTRAINT PK_REGISTRAZIONE_SENSORE
        PRIMARY KEY (SERIALE, DATA_SECONDI, NOME_PRODUTTORE),
    
    --FK 
    CONSTRAINT FK_REGISTRAZIONE_SENSORE_A_SENSORE
        FOREIGN KEY (SERIALE, NOME_PRODUTTORE)
        REFERENCES SENSORE (SERIALE, NOME_PRODUTTORE)
);