CREATE TABLE CELLA_IDROPONICA(
    CODICE_CELLA_IDR CHAR(4), --000A
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    SISTEMA_IDROPONICO VARCHAR2(30),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_CELLA_IDROPONICA_DATA_MONTAGGIO NOT NULL,
    MAX_COLTURE NUMBER(4,0)
        CONSTRAINT NN_CELLA_IDROPONICA_MAX_COLTURE NOT NULL,
    
    --PK
    CONSTRAINT PK_CELLA_IDROPONICA
        PRIMARY KEY (CODICE_CELLA_IDR, CODICE_AREA, NOME_STRUTTURA),

    --FK
    CONSTRAINT FK_CELLA_IDROPONICA_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_CELLA_IDROPONICA_CODICE_CELLA_IDR
        CHECK (REGEXP_LIKE(CODICE_CELLA_IDR, '^[0-9]{3}[A-Z]$')),
    
    CONSTRAINT CK_CELLA_IDROPONICA_MAX_COLTURE
        CHECK (MAX_COLTURE > 0)
);